name: "🚀 Continuous Deployment Request"
description: Create a ticket for a new CD request
title: Create a new CD
labels: deployment
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this deployment form!
  - type: input
    id: reponame
    attributes:
      label: "Gitub Repository"
      description: "Give name of the github repository"
      placeholder: "react-native-component"
    validations:
      required: true
  - type: input
    id: artifact_version
    attributes:
      label: "Artifact version"
      description: "Give your artifact version"
      placeholder: "0.1.0-alpha.56"
    validations:
      required: true
  - type: dropdown
    id: deployment_environment
    attributes:
      label: "Select your deployment environment"
      description: "Which environemnt to deploy to"
      options:
        - dev
        - uat
        - prod
      default: 0
    validations:
      required: true
