name: Continuous deployment

on:
  workflow_dispatch:

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: develop

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Authenticate with github package
        shell: bash
        run: |
          rm ~/.m2/settings.xml
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <activeProfiles>
            <activeProfile>github</activeProfile>
          </activeProfiles>
          <profiles>
           <profile>
            <id>github</id>
            <repositories>
            <repository>
            <id>github</id>
             <url>https://maven.pkg.github.com/susanto-dev/java-component</url>
             <snapshots>
              <enabled>true</enabled>
             </snapshots>
            </repository>
            </repositories>
           </profile>
          </profiles>
          <servers>
           <server>
            <id>github</id>
            <username>learnwithjj</username>
            <password>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</password>
           </server>
          </servers>
          </settings>
          EOF

      - name: Download Artifact from GitHub Packages
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
           echo "Download jar"
           curl -O -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://maven.pkg.github.com/susanto-dev/java-component/com/example/java-component/0.1.0-alpha.58/java-component-0.1.0-alpha.58.jar
           echo "Download pom"
           curl -O -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://maven.pkg.github.com/susanto-dev/java-component/com/example/java-component/0.1.0-alpha.58/java-component-0.1.0-alpha.58.pom
           ls

      - name: Deploy with env name
        shell: bash
        run: |
         mvn deploy:deploy-file -Dfile=./java-component-0.1.0-alpha.58.jar \
         -DgroupId=com.example \
         -DartifactId=java-component-dev \
         -Dversion=0.1.0-alpha.58 \
         -DpomFile=./java-component-0.1.0-alpha.58.pom \
         -DrepositoryId=github \
         -Durl=https://maven.pkg.github.com/susanto-dev/java-component \
         -Dtoken=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 -s ~/.m2/settings.xml
