name: Continuous deployment

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Give repository name'
        required: true
        default: 'java-component'
      version:
        description: 'Give package version'
        required: true
        default: '0.1.0-alpha.58'
      environment:
        description: 'Which env to deploy to?'
        required: true
        default: 'dev'


jobs:
  build:
    name: CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: develop

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Authenticate with github package
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          rm ~/.m2/settings.xml
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                      http://maven.apache.org/xsd/settings-1.0.0.xsd">
          <activeProfiles>
            <activeProfile>github</activeProfile>
          </activeProfiles>
          <profiles>
           <profile>
            <id>github</id>
            <repositories>
            <repository>
            <id>github</id>
             <url>https://maven.pkg.github.com/susanto-dev/java-component</url>
             <snapshots>
              <enabled>true</enabled>
             </snapshots>
            </repository>
            </repositories>
           </profile>
          </profiles>
          <servers>
           <server>
            <id>github</id>
            <username>${env.GITHUB_ACTOR}</username>
            <password>${env.GITHUB_TOKEN}</password>
           </server>
          </servers>
          </settings>
          EOF

      - name: Download Artifact from GitHub Packages
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
           echo "Download jar"
           curl -O -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://maven.pkg.github.com/susanto-dev/${github.event.inputs.repository}/com/example/${github.event.inputs.repository}/${github.event.inputs.version}/${github.event.inputs.repository}-${github.event.inputs.version}.jar
           echo "Download pom"
           curl -O -L \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer $GITHUB_TOKEN" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://maven.pkg.github.com/susanto-dev/${github.event.inputs.repository}/com/example/${github.event.inputs.repository}/${github.event.inputs.version}/${github.event.inputs.repository}-${github.event.inputs.version}.pom
           ls

      - name: Deploy with env name
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
         mvn deploy:deploy-file -Dfile=./${github.event.inputs.repository}/${github.event.inputs.version}.jar \
         -DgroupId=com.example \
         -DartifactId=${github.event.inputs.repository}-${github.event.inputs.environment} \
         -Dversion=${github.event.inputs.version} \
         -DpomFile=./${github.event.inputs.repository}-${github.event.inputs.version}.pom \
         -DrepositoryId=github \
         -Durl=https://maven.pkg.github.com/susanto-dev/java-component \
         -Dtoken=$GITHUB_TOKEN -s ~/.m2/settings.xml
