name: Add github user to a team
on:
  issues:
    types:
     - opened
     - edited
  workflow_dispatch:
    inputs:
      user:
        description: "GitHub username"
        required: true
        type: string
      team_name:
        description: "Team Name"
        required: true
        default: 'Developers'
        type: choice
        options:
         - Leads
         - Developers
jobs:
  add-user-to-team:
    if: contains(github.event.issue.labels.*.name, 'add_user_to_team') || github.event_name == 'workflow_dispatch'
    name: Add user to team
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: develop
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/ADD_USER_TO_TEAM.yml
      - name: echo inputs
        shell: bash
        env: 
          USER: ${{ steps.issue-parser.outputs.issueparser_user }}
          TEAM_NAME: ${{ steps.issue-parser.outputs.issueparser_team_name }}
          USER_WORKFLOW_DISPATCH: ${{ inputs.user }}
          TEAM_NAME_WORKFLOW_DISPATCH: ${{ inputs.team_name }}
        run: |
           if [[ "${{ github.event_name }}" == "issues" ]]; then
             echo "USER=$USER" >> $GITHUB_ENV
             echo "TEAM_NAME=$TEAM_NAME" >> $GITHUB_ENV
           else
             echo "USER=$USER_WORKFLOW_DISPATCH" >> $GITHUB_ENV
             echo "TEAM_NAME=$TEAM_NAME_WORKFLOW_DISPATCH" >> $GITHUB_ENV
           fi

      - uses: actions/github-script@v7
        if: github.event_name == 'issues'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ' 👋 Thanks for opening an issue. It will be addressed soon'
            })

      - name: Add a user to team
        shell: bash
        env:
         GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          if [ "$TEAM_NAME" == "Leads" ];then
            type="maintainer"
          else
            type="member"
          fi
          HTTP_RESPONSE=$(curl -s -o response.txt -w "%{response_code}" \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/susanto-dev/teams/$TEAM_NAME/memberships/$USER \
          -d "{\"role\":\"$type\"}")
          echo "$HTTP_RESPONSE"
          echo "PRINTING THE RESPONSE TEXT"
          cat response.txt

      - uses: actions/github-script@v7
        if: github.event_name == 'issues'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '⚡ user has been added to the team'
            })
            github.rest.issues.update({
             ...context.repo,
             issue_number: context.issue.number,
             state: "closed"
            })

